#!/bin/sh

realpath . &>/dev/null || realpath() {
    P=$1
    while readlink $P >/dev/null; do P=`readlink $P`; done
    [[ $P = /* ]] && echo "$P" || echo "$PWD/${P#./}"
}
BINDIR=$(dirname $(realpath $0))

is_service_up (){
  [ $(curl -sL -w "%{http_code}\\n" "$1" -o /dev/null) -eq "$2" ]
}

wait_for_service (){
  while ! is_service_up $1 $2  ; do
    echo "Waiting for $1"
    sleep 1
  done
}

case "$1" in
  start)
    #$BINDIR/dbus/agile-dbus-start
    $BINDIR/compose/agile-compose up -d agile-core
    $BINDIR/compose/agile-compose up -d agile-ble
    wait_for_service "http://localhost:8080" 404
    $BINDIR/compose/agile-compose up -d agile-ui
    wait_for_service "http://localhost:2000" 200
    $BINDIR/compose/agile-compose up -d agile-osjs
    wait_for_service "http://localhost:8000" 200
    $BINDIR/compose/agile-compose up -d agile-nodered
    wait_for_service "http://localhost:1880" 200
    $BINDIR/compose/agile-compose up -d agile-zb
    sleep 3
    $BINDIR/compose/agile-compose up -d agile-zb-lamp
    ;;
  stop)
    $BINDIR/compose/agile-compose stop
    ;;
  clean)
    $BINDIR/dbus/agile-dbus-stop
    $BINDIR/compose/agile-compose down
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  update)
    $BINDIR/compose/agile-compose pull
    ;;
  zb-start)
    $BINDIR/compose/agile-compose up -d agile-zb
    sleep 3
    $BINDIR/compose/agile-compose up -d agile-zb-lamp
    ;;
  zb-stop)
    $BINDIR/compose/agile-compose stop agile-zb-lamp agile-zb
    ;;
  compose)
    shift
    $BINDIR/compose/agile-compose "$@"
    ;;
  install)
    ln -s $BINDIR/agile /usr/local/bin/
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|clean|update|compose|install}
         install: create symbolic link in /usr/local/bin
         start: start all AGILE components
         stop: stop all AGILE components
         restart: stop and then start
         clean: stop and remove all containers. AGILE persistent state will remain, but docker containers will be reinitialized
         update: download newest version of docker containers
         compose: use docker-compose commands for fine-grained control (e.g. docker compose logs)
    "
    exit 1
    ;;
esac
