#!/bin/bash

realpath . &>/dev/null || realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}
export BINDIR=$(dirname $(realpath $0))
[ -r "$BINDIR/agile.config" ] && . "$BINDIR/agile.config"

export COMPOSE_HTTP_TIMEOUT=300
export AGILE_CLIENT_PORT=2000
export AGILE_ZB_TTY=/dev/ttyUSB0

if [ "$AGILE_MODE" == "remote" ]
then
  AGILE_HOST=${AGILE_HOST:-"resin.local"}

  # Agile-ble runs the bluetooth service so we must stop the hosts
  ssh root@$AGILE_HOST -p22222 'systemctl stop bluetooth'

  export DOCKER_API_VERSION=1.22
  export DOCKER_HOST=tcp://$AGILE_HOST:2375
  # Because resinos is read-only fs we must write to /mnt/data/
  export DATA=/mnt/data/.agile
  export DBUS_SYSTEM_SOCKET=/var/run/dbus/system_bus_socket
  export DBUS_SESSION_SOCKET_DIR=$DATA/agile_bus/
  export DBUS_SESSION_SOCKET_NAME=agile_bus_socket
  export DBUS_SESSION_SOCKET=$DBUS_SESSION_SOCKET_DIR/$DBUS_SESSION_SOCKET_NAME
  export DBUS_SESSION_BUS_ADDRESS=unix:path=$DBUS_SESSION_SOCKET
else
  export DATA=$HOME/.agile
  export DBUS_SYSTEM_SOCKET=/var/run/dbus/system_bus_socket
  export DBUS_SESSION_SOCKET_DIR=$DATA/agile_bus/
  export DBUS_SESSION_SOCKET_NAME=agile_bus_socket
  export DBUS_SESSION_SOCKET=$DBUS_SESSION_SOCKET_DIR/$DBUS_SESSION_SOCKET_NAME
  export ARCH=`uname -m`
fi

cd $BINDIR
docker-compose "$@"
