#!/bin/bash

realpath . &>/dev/null || realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}
export BINDIR=$(dirname $(realpath $0))

export COMPOSE_HTTP_TIMEOUT=300

export AGILE_CLIENT_PORT=2000

export AGILE_ZB_TTY=/dev/ttyUSB0

export DBUS_SYSTEM_SOCKET=/var/run/dbus/system_bus_socket
export DBUS_SESSION_SOCKET_DIR=$HOME/.agile/agile_bus/
export DBUS_SESSION_SOCKET_NAME=agile_bus_socket
export DBUS_SESSION_SOCKET=$DBUS_SESSION_SOCKET_DIR/$DBUS_SESSION_SOCKET_NAME
export ARCH=`uname -m`

case $ARCH in
  armv7l )
    export IMAGE_INFLUXDB=sbiermann/rpi-influxdb
    export IMAGE_GRAFANA=fg2it/grafana-armhf:v3.1.1
    ;;
  x86_64 )
    export IMAGE_INFLUXDB=influxdb
    export IMAGE_GRAFANA=grafana/grafana:3.1.1
    ;;
  * )
    export IMAGE_INFLUXDB=influxdb
    export IMAGE_GRAFANA=grafana/grafana:3.1.1
    ;;
esac

cd $BINDIR
docker-compose "$@"
